DROP TABLE IF EXISTS raw_export_data;

CREATE TABLE raw_export_data (
    `Fiscal Year` TEXT,
    `Unique Identifier` TEXT,
    `Deal Number` TEXT,
    `Decision` TEXT,
    `Decision Date` TEXT,
    `Effective Date` TEXT,
    `Expiration Date` TEXT,
    `Brokered` TEXT,
    `Deal Cancelled` TEXT,
    `Country` TEXT,
    `Program` TEXT,
    `Policy Type` TEXT,
    `Decision Authority` TEXT,
    `Primary Export Product NAICS/SIC code` TEXT,
    `Product Description` TEXT,
    `Term` TEXT,
    `Primary Applicant` TEXT,
    `Primary Lender` TEXT,
    `Primary Exporter` TEXT,
    `Primary Exporter City` TEXT,
    `Primary Exporter State Code` TEXT,
    `Primary Exporter State Name` TEXT,
    `Primary Borrower` TEXT,
    `Primary Source of Repayment (PSOR)` TEXT,
    `Working Capital Delegated Authority` TEXT,
    `Approved/Declined Amount` TEXT,
    `Disbursed/Shipped Amount` TEXT,
    `Undisbursed Exposure Amount` TEXT,
    `Outstanding Exposure Amount` TEXT,
    `Small Business Authorized Amount` TEXT,
    `Woman Owned Authorized Amount` TEXT,
    `Minority Owned Authorized Amount` TEXT,
    `Loan Interest Rate` TEXT,
    `Multiyear Working Capital Extension` TEXT
);
select * from raw_export_data;
